import {defineConfig} from 'eslint/config';
import globals from 'globals';
import js from '@eslint/js';
import {MAX_PARAMS, MAX_STATEMENTS} from './constants.js';

export const base = defineConfig([
    {
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                ...globals.es2021,
                ...globals.jest,
                ...globals.mocha,
                globalThis: false
            },
            parserOptions: {ecmaFeatures: {jsx: true}}
        },
        settings: {react: {version: 'detect'}}
    },
    js.configs.recommended,
    [{
        rules: {
        // ── ES5 core rules ── //
            'accessor-pairs': 'off',
            'block-scoped-var': 'error',
            'camelcase': ['error', {properties: 'never'}],
            'capitalized-comments': 'off',
            'class-methods-use-this': 'off',
            'complexity': 'off',
            'consistent-return': 'error',
            'consistent-this': ['error', 'self'],
            'curly': ['error', 'all'],
            'default-case': 'error',
            'dot-notation': ['error', {allowKeywords: true}],
            'eqeqeq': 'error',
            'func-name-matching': 'off',
            'func-names': 'off',
            'func-style': ['off', 'declaration'],
            'guard-for-in': 'error',
            'id-length': 'off',
            'init-declarations': 'off',
            'max-depth': ['error', 2],
            'max-lines': 'off',
            'max-nested-callbacks': ['off', 2],
            'max-params': ['error', MAX_PARAMS],
            'max-statements': ['error', MAX_STATEMENTS],
            'new-cap': 'off',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': 'error',
            'no-console': 'error',
            'no-constant-condition': 'error',
            'no-continue': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-delete-var': 'error',
            'no-div-regex': 'error',
            'no-dupe-keys': 'error',
            'no-dupe-args': 'error',
            'no-duplicate-case': 'error',
            'no-else-return': 'error',
            'no-empty': 'error',
            'no-empty-character-class': 'error',
            'no-empty-function': 'off',
            'no-empty-pattern': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-ex-assign': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-boolean-cast': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-global-assign': 'off',
            'no-implicit-coercion': 'error',
            'no-implied-eval': 'error',
            'no-inline-comments': 'off',
            'no-inner-declarations': ['error', 'functions'],
            'no-invalid-regexp': 'error',
            'no-invalid-this': 'off',
            'no-irregular-whitespace': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': ['error', {
                allowLoop: true,
                allowSwitch: true
            }],
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-multi-assign': 'off',
            'no-multi-str': 'error',
            'no-negated-condition': 'off',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-obj-calls': 'error',
            'no-octal': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-plusplus': ['error', {allowForLoopAfterthoughts: true}],
            'no-proto': 'error',
            'no-prototype-builtins': 'off',
            'no-redeclare': 'error',
            'no-regex-spaces': 'error',
            'no-restricted-properties': 'off',
            'no-restricted-syntax': 'off',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-shadow': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-template-curly-in-string': 'off',
            'no-ternary': 'off',
            'no-throw-literal': 'error',
            'no-undef': 'error',
            'no-undef-init': 'off',
            'no-undefined': 'off',
            'no-unexpected-multiline': 'error',
            'no-underscore-dangle': 'off',
            'no-unneeded-ternary': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unused-expressions': ['error', {allowTernary: true}],
            'no-unused-vars': [
                'error',
                {
                    args: 'after-used',
                    ignoreRestSiblings: true,
                    vars: 'all',
                    argsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                    destructuredArrayIgnorePattern: '^_',
                    varsIgnorePattern: '^_'
                }
            ],
            'no-use-before-define': 'error',
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-useless-escape': 'error',
            'no-useless-return': 'error',
            'no-void': 'off',
            'no-warning-comments': 'off',
            'no-with': 'error',
            'no-magic-numbers': ['error', {ignore: [-1, 0, 1, 2]}],
            'one-var': ['error', {
                var: 'always',
                let: 'always',
                const: 'never'
            }],
            'operator-assignment': 'off',
            'radix': ['error', 'always'],
            'id-match': 'off',
            'sort-keys': 'off',
            'sort-vars': 'off',
            'strict': 'off',
            'unicode-bom': 'off',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'vars-on-top': 'error',
            'yoda': ['error', 'never'],

            // ── ES6 rules ──
            'arrow-body-style': 'off',
            'constructor-super': 'error',
            'no-class-assign': 'error',
            'no-const-assign': 'error',
            'no-dupe-class-members': 'error',
            'no-duplicate-imports': ['error', {includeExports: true}],
            'no-this-before-super': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-rename': 'error',
            'no-var': 'error',
            'object-shorthand': ['error', 'always'],
            'prefer-arrow-callback': 'off',
            'prefer-const': 'error',
            'prefer-destructuring': 'off',
            'prefer-numeric-literals': 'off',
            'prefer-promise-reject-errors': 'off',
            'prefer-spread': 'off',
            'prefer-template': 'error',
            'require-yield': 'error',
            'symbol-description': 'error',

            // ── ES8 rules ──
            'no-await-in-loop': 0

        }
    }]
]);
